# ADDITION
# Can suggest/enforce style preferences for future contributions
---
require:
  - rubocop-rails

AllCops:
  Exclude:
    - db/schema.rb
    - bin/*
  EnabledByDefault: true
Bundler/GemComment:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/RedundantLineBreak:
  Enabled: false
Lint/ConstantResolution:
  Enabled: false
Metrics/MethodLength:
  Max: 20
  Exclude:
    - config/*
Rails/Blank:
  Enabled: false
Style/Copyright:
  Enabled: false
Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/MissingElse:
  Exclude:
    - config/*
Style/MethodCallWithArgsParentheses:
  Enabled: false
